<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>LoopGolem.Desktop</RootNamespace>
    <AssemblyName>loopgolem-desktop</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <ProjectReference Include="..\LoopGolem.Core\LoopGolem.Core.csproj" />
  </ItemGroup>
</Project>
